# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Import Datetime class
from datetime import datetime

def index(request):

    # Some Date Object, for example a default generated by datetime
    myDate = datetime.now()

    # Render Some Template with a parameter accesible as date
    return render(request, 'template.html', {
        'date': myDate
    })